BABIES<-read.table("D:/College/StatKom/Babies.data",header=TRUE)
BABIES<-read.table("/media/michael/New Volume/College/StatKom/Babies.data",header=TRUE)
CLEAN<-subset(BABIES,bwt!=999 & gestation!=999 & parity!=9 & height!=99 & weight!=999 & smoke!=9)

NONSMOKER<-subset(CLEAN,smoke!="1")	
SMOKER<-subset(CLEAN,smoke!="0")

par(mfrow=c(2,1))
densityNonSmoke<-hist(NONSMOKER$bwt,main="Density Histogram for Babies Birth Weight",xlab="Birth Weight", xlim=c(30,180),las=1, breaks=10, freq=FALSE)
box()
lines(density(NONSMOKER$bwt),col = 1, lwd = 1)
densitySmoke<-hist(SMOKER$bwt,main="Density Histogram for Babies Birth Weight",xlab="Birth Weight",xlim=c(30,180),las=1,breaks=10,freq=FALSE)
box()
lines(density(SMOKER$bwt),col = 1, lwd = 1)

x<-mean(NONSMOKER$bwt)
y<-mean(SMOKER$bwt)
x-y

require(lattice)
par(mfrow=c(1,2))
boxplot(NONSMOKER$bwt, ylab="Weight",main="NonSmoker")
boxplot(SMOKER$bwt, ylab="Weight", main="Smoker")
bwplot(smoke ~ bwt, data = CLEAN, xlab = "number of nonsmoker", ylab = "baby weight")

x<-median(NONSMOKER$bwt)
y<-median(SMOKER$bwt)
x-y

FIRSTBORN<-subset(CLEAN,parity==0)
NOTFIRSTBORN<-subset(CLEAN,parity!=0)
x<-median(FIRSTBORN$bwt)
y<-median(NOTFIRSTBORN$bwt)
x-y

par(mfrow=c(1,1))
PrePregnancyNonSmoke<-density(NONSMOKER$weight)
plot(PrePregnancyNonSmoke,main="Density Graph for Pre Pregnancy Mother",xlab="weight",col="green")
par(new=TRUE)
PrePregnancySmoke<-density(SMOKER$weight)
plot(PrePregnancySmoke,main="Density Graph for Pre Pregnancy Mother",xlab="weight",col="red")
ket <- factor(PrePregnancySmoke, levels= c(0,1),labels = c("Smoker", "NonSmoker")) 
colfill<-c(2:(2+length(levels(ket))))
legend(locator(1), levels(ket), fill=colfill)

x<-mean(NONSMOKER$weight)
y<-mean(SMOKER$weight)
x-y

weightKg<-CLEAN$weight*0.453592
heightM<-CLEAN$height*0.0254
CLEANP<-weightKg/(heightM*heightM)
CLEAN$bwi <- CLEANP

NONSMOKER<-subset(CLEAN,smoke!="1")
SMOKER<-subset(CLEAN,smoke!="0")

BAWAHQ1NONSMOKE<-subset(NONSMOKER,bwi<=quantile(NONSMOKER$bwi,0.25))
NOLQ1NONSMOKE<-mean(BAWAHQ1NONSMOKE$bwt)
NOLQ1NONSMOKE
sd(BAWAHQ1NONSMOKE$bwt)
median(BAWAHQ1NONSMOKE$bwt)
IQR(BAWAHQ1NONSMOKE$bwt)
BAWAHQ1SMOKE<-subset(SMOKER,bwi<=quantile(SMOKER$bwt,0.25))
NOLQ1SMOKE<-mean(BAWAHQ1SMOKE$bwt)
NOLQ1SMOKE
sd(BAWAHQ1SMOKE$bwt)
median(BAWAHQ1SMOKE$bwt)
IQR(BAWAHQ1SMOKE$bwt)

ATASQ1NONSMOKE<-subset(NONSMOKER,bwi>quantile(NONSMOKER$bwi,0.25)&bwi<quantile(NONSMOKER$bwi,0.5))
Q1Q2NONSMOKE<-mean(ATASQ1NONSMOKE$bwt)
Q1Q2NONSMOKE
sd(ATASQ1NONSMOKE$bwt)
median(ATASQ1NONSMOKE$bwt)
IQR(ATASQ1NONSMOKE$bwt)
ATASQ1SMOKE<-subset(SMOKER,bwi>quantile(SMOKER$bwi,0.25)&bwi<quantile(SMOKER$bwi,0.5))
Q1Q2SMOKE<-mean(ATASQ1SMOKE$bwt)
Q1Q2SMOKE
sd(ATASQ1SMOKE$bwt)
median(ATASQ1SMOKE$bwt)
IQR(ATASQ1SMOKE$bwt)

ATASQ2NONSMOKE<-subset(NONSMOKER,bwi>quantile(NONSMOKER$bwi,0.5)&bwi<quantile(NONSMOKER$bwi,0.75))
Q2Q3NONSMOKE<-mean(ATASQ2NONSMOKE$bwt)
Q2Q3NONSMOKE
sd(ATASQ2NONSMOKE$bwt)
median(ATASQ2NONSMOKE$bwt)
IQR(ATASQ2NONSMOKE$bwt)
ATASQ2SMOKE<-subset(SMOKER,bwi>quantile(SMOKER$bwi,0.5)&bwi<quantile(SMOKER$bwi,0.75))
Q2Q3SMOKE<-mean(ATASQ2SMOKE$bwt)
Q2Q3SMOKE
sd(ATASQ2SMOKE$bwt)
median(ATASQ2SMOKE$bwt)
IQR(ATASQ2SMOKE$bwt)

ATASQ3NONSMOKE<-subset(NONSMOKER,bwi>quantile(NONSMOKER$bwi,0.75)&bwi<quantile(NONSMOKER$bwi,1))
Q3MAXNONSMOKE<-mean(ATASQ3NONSMOKE$bwt)
Q3MAXNONSMOKE
sd(ATASQ3NONSMOKE$bwt)
median(ATASQ3NONSMOKE$bwt)
IQR(ATASQ3NONSMOKE$bwt)
ATASQ3SMOKE<-subset(SMOKER,bwi>quantile(SMOKER$bwi,0.75)&bwi<quantile(SMOKER$bwi,1))
Q3MAXSMOKE<-mean(ATASQ3SMOKE$bwt)
Q3MAXSMOKE
sd(ATASQ3SMOKE$bwt)
median(ATASQ3SMOKE$bwt)
IQR(ATASQ3SMOKE$bwt)

par(mfrow=c(1,2))
boxplot(BAWAHQ1NONSMOKE$bwt,ylab="Baby Birth Weight",main="Non-Smoker")
boxplot(BAWAHQ1SMOKE$bwt,ylab="Baby Birth Weight",main="Smoker")
par(mfrow=c(1,2))
boxplot(ATASQ1NONSMOKE$bwt,ylab="Baby Birth Weight",main="Non-Smoker")
boxplot(ATASQ1SMOKE$bwt,ylab="Baby Birth Weight",main="Smoker")
par(mfrow=c(1,2))
boxplot(ATASQ2NONSMOKE$bwt,ylab="Baby Birth Weight",main="Non-Smoker")
boxplot(ATASQ2SMOKE$bwt,ylab="Baby Birth Weight",main="Smoker")
par(mfrow=c(1,2))
boxplot(ATASQ3NONSMOKE$bwt,ylab="Baby Birth Weight",main="Non-Smoker")
boxplot(ATASQ3SMOKE$bwt,ylab="Baby Birth Weight",main="Smoker")

x<-lm(bwi~bwt,data=BAWAHQ1NONSMOKE)
summary(x)
with(BAWAHQ1NONSMOKE,plot(bwt,bwi))
abline(x)

par(mfrow=c(1,3))
with(BAWAHQ1NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Min-Q1 Non-Smoker",pch=8))
x<-lm(bwi~bwt,data=BAWAHQ1NONSMOKE)
abline(x)
with(BAWAHQ1NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Min-Q1 Non-Smoker",pch=8))
y<-lqs(bwi~bwt,data=BAWAHQ1NONSMOKE)
abline(y)
with(BAWAHQ1NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Min-Q1 Non-Smoker",pch=8))
z<-rlm(bwi~bwt,data=BAWAHQ1NONSMOKE)
abline(z)

par(mfrow=c(1,3))
with(BAWAHQ1SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Min-Q1 Smoker",pch=8))
x<-lm(bwi~bwt,data=BAWAHQ1SMOKE)
abline(x)
with(BAWAHQ1SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Min-Q1 Smoker",pch=8))
y<-lqs(bwi~bwt,data=BAWAHQ1SMOKE)
abline(y)
with(BAWAHQ1SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Min-Q1 Smoker",pch=8))
z<-rlm(bwi~bwt,data=BAWAHQ1SMOKE)
abline(z)

par(mfrow=c(1,3))
with(ATASQ1NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q1-Q2 Non-Smoker",pch=8))
x<-lm(bwi~bwt,data=ATASQ1NONSMOKE)
abline(x)
with(ATASQ1NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q1-Q2 Non-Smoker",pch=8))
y<-lqs(bwi~bwt,data=ATASQ1NONSMOKE)
abline(y)
with(ATASQ1NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q1-Q2 Non-Smoker",pch=8))
z<-rlm(bwi~bwt,data=ATASQ1NONSMOKE)
abline(z)

par(mfrow=c(1,3))
with(ATASQ1SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q1-Q2 Smoker",pch=8))
x<-lm(bwi~bwt,data=ATASQ1SMOKE)
abline(x)
with(ATASQ1SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q1-Q2 Smoker",pch=8))
y<-lqs(bwi~bwt,data=ATASQ1SMOKE)
abline(y)
with(ATASQ1SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q1-Q2 Smoker",pch=8))
z<-rlm(bwi~bwt,data=ATASQ1SMOKE)
abline(z)

par(mfrow=c(1,3))
with(ATASQ2NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q2-Q3 Non-Smoker",pch=8))
x<-lm(bwi~bwt,data=ATASQ2NONSMOKE)
abline(x)
with(ATASQ2NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q2-Q3 Non-Smoker",pch=8))
y<-lqs(bwi~bwt,data=ATASQ2NONSMOKE)
abline(y)
with(ATASQ2NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q2-Q3 Non-Smoker",pch=8))
z<-rlm(bwi~bwt,data=ATASQ2NONSMOKE)
abline(z)

par(mfrow=c(1,3))
with(ATASQ2SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q2-Q3 Smoker",pch=8))
x<-lm(bwi~bwt,data=ATASQ2SMOKE)
abline(x)
with(ATASQ2SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q2-Q3 Smoker",pch=8))
y<-lqs(bwi~bwt,data=ATASQ2SMOKE)
abline(y)
with(ATASQ2SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q2-Q3 Smoker",pch=8))
z<-rlm(bwi~bwt,data=ATASQ2SMOKE)
abline(z)

par(mfrow=c(1,3))
with(ATASQ3NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q3-Max Non-Smoker",pch=8))
x<-lm(bwi~bwt,data=ATASQ3NONSMOKE)
abline(x)
with(ATASQ3NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q3-Max Non-Smoker",pch=8))
y<-lqs(bwi~bwt,data=ATASQ3NONSMOKE)
abline(y)
with(ATASQ3NONSMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q3-Max Non-Smoker",pch=8))
z<-rlm(bwi~bwt,data=ATASQ3NONSMOKE)
abline(z)

par(mfrow=c(1,3))
with(ATASQ3SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q3-Max Smoker",pch=8))
x<-lm(bwi~bwt,data=ATASQ3SMOKE)
abline(x)
with(ATASQ3SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q3-Max Smoker",pch=8))
y<-lqs(bwi~bwt,data=ATASQ3SMOKE)
abline(y)
with(ATASQ3SMOKE,plot(bwt,bwi,ylab="Babies Weight",xlab="Body Weight Index",main="Q3-Max Smoker",pch=8))
z<-rlm(bwi~bwt,data=ATASQ3SMOKE)
abline(z)
